version: '3.8'

services:
  webserver:
    depends_on:
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  frontend: 
    build: 
      dockerfile: Dockerfile
      context: './frontend'
    volumes:
      - /usr/app/frontend/node_modules
      - ./frontend:/usr/app/frontend
      - /usr/app/frontend/.next
    ports:
      - "3000:3000"
